### ISSUE TITLE
Error in tutorial_quanvolution.py 

### ISSUE THREAD

**Issue by charujing** [XanaduAI/qml#69]
Hi,
When I try "python tutorial_quanvolution.py ", it echos this problem. Could anyone can help me?
Thanks.
2020-04-17 15:35:02.466789: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /public/software/gnu/gcc/v7.2.0/lib64:/public/software/nvidia/cudnn/9.0/lib64:/usr/lib64/nvidia:/usr/local/cuda-9.0/lib64:/usr/local/cuda-9.0/nvvm/lib64:/opt/gridview//pbs/dispatcher/lib::/usr/local/lib64:/usr/local/lib
2020-04-17 15:35:02.491135: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /public/software/gnu/gcc/v7.2.0/lib64:/public/software/nvidia/cudnn/9.0/lib64:/usr/lib64/nvidia:/usr/local/cuda-9.0/lib64:/usr/local/cuda-9.0/nvvm/lib64:/opt/gridview//pbs/dispatcher/lib::/usr/local/lib64:/usr/local/lib
2020-04-17 15:35:02.491172: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.

Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11493376/11490434 [==============================] - 1s 0us/step
Quantum pre-processing of train images:
50/50        
Quantum pre-processing of test images:
Traceback (most recent call last):
  File "tutorial_quanvolution.py", line 224, in <module>
    np.save(SAVE_PATH + "q_train_images.npy", q_train_images)
  File "/home/zhangxiaochu/zharj/.local/lib/python3.6/site-packages/autograd/tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
  File "/public/software/bio/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 524, in save
    fid = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'quanvolution/q_train_images.npy'

**Comment by josh146** [comment]
Hi @charujing! You will need to create the directory to store the output trained data. In this case, it looks like the directory should be called `quanvolution/`. Creating this directory before executing the script will allow it to work:

```console
mkdir quanvolution
python tutorial_quanvolution.py
```
